language: node_js
node_js:
- stable
- '12'
- '11'
- '10'
before_deploy:
- npm version --no-git-tag-version --force $(npx semver -i minor $(npm info pinyin-utils version))
deploy:
  provider: npm
  email: mail@pepebecker.com
  api_key: ${NPM_TOKEN}
  skip_cleanup: true
  on:
    branch: master
    node: stable
